#!/usr/bin/env bash
# Bash script containing commands to automatically configure a Ubuntu machine to
# configure a Nginx server so that /redirect_me is redirecting to another page
sudo ./1-install_nginx_web_server
sudo sed -i "/listen \[\:\:\]\:80 default_server;/a rewrite ^/redirect_me
     https://www.youtube.com permanent;" /etc/nginx/sites-available/default
