#!/usr/bin/env bash
# This script creates the file /var/run/holbertonscript.pid containing its PID
# displays "To infinity and beyond indefinitely", displays
# "I hate the kill command" when receiving a SIGTERM signal, displays
# "Y U no love me?!" when receiving a SIGINT signal, deletes the file
# /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or
# SIGTERM signal

count=1

PIDFILE="/var/run/holbertonscript.pid"
touch $PIDFILE
echo $$ > $PIDFILE

trap 'echo I hate the kill command; rm $PIDFILE; kill -SIGKILL $$' SIGTERM
trap 'echo Y U no love me?!; kill -SIGKILL $$' SIGINT

trap 'rm $PIDFILE; kill -SIGKILL $$' SIGQUIT

while [ $count ]
do
    echo "To infinity and beyond"
    sleep 2
done
