#!/usr/bin/env bash
# This script displays the username, user id, & home directory path for the
# user of the file /etc/passwd.

filepath="/etc/passwd"
while IFS= read -r line
do
  echo "$line" | cut -d ":" -f1,3,6
done < "$filepath"
