#!/usr/bin/env bash
# This script gives information about the "holbertonschool" file

filename="holbertonschool"

if [ -a "$filename" ]
then
	echo "holbertonschool file exists"
	if [ -s "$filename" ]
	then
	    echo "holbertonschool file is not empty"
	else
	    echo "holbertonschool file is empty"
	fi

	if [ -f "$filename" ]
	then
	    echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
